# Generated by Django 2.1 on 2021-01-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
